version: '3'
services:
  web:
    build: .
    depends_on:
      - db
    volumes:
      - .:/task_manager:cached
      - bundle_cache:/bundle_cache
    ports:
      - 3000:3000
    environment:
      BUNDLE_PATH: /bundle_cache
  db:
    image: postgres:10.3-alpine

volumes:
  bundle_cache:
